---
- name: Create modlist installation directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Wabbajack/WelcomeToParadise"
    state: directory

- name: Download modlist
  ansible.builtin.get_url:
    url: "https://github.com/Omni-guides/Wabbajack-Modlist-Linux/releases/download/1.1.1/Welcome_to_Paradise.wabbajack"
    dest: "{{ ansible_env.HOME }}/Wabbajack/WelcomeToParadise/Welcome_to_Paradise.wabbajack"

- name: Run Wabbajack to install modlist
  ansible.builtin.command:
    cmd: "wine Wabbajack.exe --auto-install WelcomeToParadise/Welcome_to_Paradise.wabbajack"
    chdir: "{{ ansible_env.HOME }}/Wabbajack"
